### PR TITLE
adding props to the VCreateExerciseButton component

### PR DESCRIPTION
**Pull request by sweetcuptea**
**What issue/feature/bugfix/improvement did you solve?**
---
I want to make the `VCreateExerciseButton` component more dynamic when we want to add a link that will be directed to that component.

**How you resolve the issue**
---
Add a `pathUrl` props to the `VCreateExerciseButton` component with a default empty string instead of writing the link directly to the component

### CODE REVIEW

**Comment by trihargianto** [comment]
> make the VCreateExerciseButton component more dynamic when we want to add a link that will be directed to that component.

Your component name now becomes ambiguous because it’s not just to create exercises, but able to redirect to another page too. Please consider to change the component name using more generic name.

**Comment by sweetcuptea** [comment]
> > make the VCreateExerciseButton component more dynamic when we want to add a link that will be directed to that component.
> 
> Your component name now becomes ambiguous because it’s not just to create exercises, but able to redirect to another page too. Please consider to change the component name using more generic name.
> 
> For example VButton.

I apologize for the confusion here.

This component is a unique round button and is not like a regular button, I will show it in the picture below :

| Circle Button | Regular Button |
| --- | --- |
| image | 
image |

**Comment by trihargianto** [comment]
> > > make the VCreateExerciseButton component more dynamic when we want to add a link that will be directed to that component.
> > 
> > 
> > Your component name now becomes ambiguous because it’s not just to create exercises, but able to redirect to another page too. Please consider to change the component name using more generic name.
> > For example VButton.
> 
> I apologize for the confusion here.
> 
> This component is a unique round button and is not like a regular button, I will show it in the picture below :
> 
> Circle Button	Regular Button
> image	image

So why you want to add a prop for this component? I mean this is a button with “+” icon on it.

**Comment by sweetcuptea** [comment]
> > > > make the VCreateExerciseButton component more dynamic when we want to add a link that will be directed to that component.
> > > 
> > > 
> > > Your component name now becomes ambiguous because it’s not just to create exercises, but able to redirect to another page too. Please consider to change the component name using more generic name.
> > > For example VButton.
> > 
> > 
> > I apologize for the confusion here.
> > This component is a unique round button and is not like a regular button, I will show it in the picture below :
> > Circle Button	Regular Button
> > image	image
> 
> So why you want to add a prop for this component? I mean this is a button with “+” icon on it.

I didn't think I would give props to that component before.

then I thought that if I want to use the component again, I can give a different link to the component.

but if you don't think it's necessary and doesn't make sense you can cancel the commit.

**Comment by trihargianto** [comment]
> > So why you want to add a prop for this component? I mean this is a button with “+” icon on it.
> 
> I didn't think I would give props to that component before. and then I think that if I want to use the component again, I can give a different link to the component. but if you don't think it's necessary and doesn't make sense you can cancel the commit.

Hmmm, WILL you use this component with different link? or you don’t know yet

**Comment by sweetcuptea** [comment]
> Hmmm, will you use this component with different link? or you don’t know yet

sorry I think I am going cancel this pull request

**Pull request closed without merging**
