### PR TITLE
organizing icon component

### PR DESCRIPTION
**Pull request by sweetcuptea**
**What issue/feature/bugfix/improvement did you solve?**
---
When I have a lot of icon components, it would be very inconvenient if I had to import them one by one in a component even though they have the same directory. It would be easier to import multiple icons in one line of code.

**How you resolve the issue**
---
So I created `index.js` to make it easier when calling multiple icons in a component. 
- before
   ```javascript
    import IconComponent1 from "../IconComponents";
    import IconComponent2 from "../IconComponents";
    import IconComponent3 from "../IconComponents";
    ```
- after
    ```javascript
    import { IconComponent1 , IconComponent2, IconComponent3 } from "../IconComponents";
    ```

### CODE REVIEW

**Comment by trihargianto** [comment]
good approach 👍 

Anyway, it would be better if you rename your `Icon.js` name becomes `index.js`. 
so you will be able to import the icon like this

```vue
import { VBarbleOff } from "../atoms/IconComponents";
```

**Comment by sweetcuptea** [comment]
> good approach 👍
> 
> Anyway, it would be better if you rename your `Icon.js` name becomes `index.js`. so you will be able to import the icon like this
> 
> ```
> import { VBarbleOff } from "../atoms/IconComponents";
> ```

sure, thanks for the advice 😁

**Comment by trihargianto** [comment]
Please update the PR description when you update the code.

**Comment by trihargianto** [comment]
Looks mantap from me 🔥

**Review by trihargianto — APPROVED** [review]

**Comment by sweetcuptea** [comment]
> Please update the PR description when you update the code.

ah okay sorry, thanks for the advice

**Pull request merged**
